### ISSUE TITLE
Android Build - OverrideUnityActivity is defined Multiple Times

### ISSUE THREAD

**Issue by teatherconsulting** [alantom1423/cordova-plugin-unityar#1]
I've been using your plugin and it is working perfectly for iOS.  However, whenever I build the Android app I get the error below.  Have you run into this before or do you have any ideas on how it might be solved?

 Task :app:mergeDexRelease FAILED
AGPBI: {"kind":"error","text":"Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex","sources":[{"file":"/Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex"}],"tool":"D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:441)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.W.a(:87)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	... 33 more
Caused by: com.android.tools.r8.utils.b: Error: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex
	at Version.fakeStackEntry(Version_2.0.74.java:0)
	at com.android.tools.r8.utils.M0.a(:21)
	at com.android.tools.r8.utils.L0.b(:7)
	at com.android.tools.r8.utils.L0.a(:27)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete

	at com.android.tools.r8.utils.L0.a(:10)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.L0.a(:6)
	at com.android.tools.r8.graph.D0$c.f(:3)
	at com.android.tools.r8.dex.a.a(:83)
	at com.android.tools.r8.dex.a.a(:10)
	at com.android.tools.r8.D8.d(:6)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.W.a(:30)
Caused by: com.android.tools.r8.utils.b: Error: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex

**Comment by alantom1423** [comment]
Hi @teatherconsulting  did you run this by cordova run android in command prompt? Have you tried opening the project in Android Studio.

**Comment by pauloagsantos** [comment]
Hi.,
how we can call the "public void quitUnity(string feedbackMsg)" method in Unity project to return to cordova.

**Comment by alantom1423** [comment]
Hi @pauloagsantos 
      Create an empty gameobject in your scene. Attach this _CordovaComm.cs_ script. Now you will be able to access this quitUnity(feedbackMsg) method. You can find the  _CordovaComm.cs_ script in files folder in this repo. Hope this helps

**Comment by alantom1423** [comment]
> I've been using your plugin and it is working perfectly for iOS. However, whenever I build the Android app I get the error below. Have you run into this before or do you have any ideas on how it might be solved?
> 
> Task :app:mergeDexRelease FAILED AGPBI: {"kind":"error","text":"Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex","sources":[{"file":"/Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex"}],"tool":"D8"} com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes. Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132) at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119) at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102) at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:441) at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242) at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57) at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63) at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67) at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63) at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97) at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63) at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44) at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41) at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409) at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399) at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150) at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94) at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36) at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41) at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60) at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215) at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164) at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64) at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56) at java.lang.Thread.run(Thread.java:748) Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete at com.android.tools.r8.utils.W.a(:87) at com.android.tools.r8.D8.run(:11) at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117) ... 33 more Caused by: com.android.tools.r8.utils.b: Error: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex at Version.fakeStackEntry(Version_2.0.74.java:0) at com.android.tools.r8.utils.M0.a(:21) at com.android.tools.r8.utils.L0.b(:7) at com.android.tools.r8.utils.L0.a(:27) Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
> 
> ```
> at com.android.tools.r8.utils.L0.a(:10)
> at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
> at com.android.tools.r8.utils.L0.a(:6)
> at com.android.tools.r8.graph.D0$c.f(:3)
> at com.android.tools.r8.dex.a.a(:83)
> at com.android.tools.r8.dex.a.a(:10)
> at com.android.tools.r8.D8.d(:6)
> at com.android.tools.r8.D8.b(:1)
> at com.android.tools.r8.utils.W.a(:30)
> ```
> 
> Caused by: com.android.tools.r8.utils.b: Error: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, Type com.company.product.OverrideUnityActivity is defined multiple times: /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/app/build/intermediates/project_dex_archive/release/out/com/company/product/OverrideUnityActivity.dex, /Users/tcmachi02/Documents/Repositories/CharityDynamics/bf-builds/build_stjrun_android_20210719/stjrun/platforms/android/unityLibrary/build/.transforms/a857f59cb56d25f6c5d572db6899672b/classes/classes.dex

Were you able t

**Comment by alantom1423** [comment]
Hi @teatherconsulting 
      Were you able to fix your issue. Try opening the project in Android Studio. Clean the project. Hope this will fix it
